---
- hosts: microk8s_server
  become: yes
  gather_facts: true
  
  tasks:

    - name: Create a directory darkbot-prod if it does not exist
      ansible.builtin.file:
        path: /mnt/darkbot-prod
        state: directory

    - name: Scale down darkbot-prod
      shell: microk8s kubectl scale deploy darkbot-deploy --namespace=darkbot-prod --replicas 0

    - name: Sleep until termination
      shell: sleep 60

    - name: Restore darkbot-prod
      ansible.builtin.copy:
        src: backups/darkbot-prod/channels.json
        dest: /mnt/darkbot-prod/channels.json

    - name: Scale up darkbot-prod
      shell: microk8s kubectl scale deploy darkbot-deploy --namespace=darkbot-prod --replicas 1