---
- hosts: microk8s_server
  become: yes
  gather_facts: true
  
  tasks:

    - name: Create a directory darkbot-dev if it does not exist
      ansible.builtin.file:
        path: /mnt/darkbot-dev
        state: directory

    - name: Scale down darkbot-dev
      shell: microk8s kubectl scale deploy darkbot-deploy --namespace=darkbot-dev --replicas 0

    - name: Sleep until termination
      shell: sleep 60

    - name: Restore darkbot-dev
      ansible.builtin.copy:
        src: backups/darkbot-dev/channels.json
        dest: /mnt/darkbot-dev/channels.json

    - name: Scale up darkbot-dev
      shell: microk8s kubectl scale deploy darkbot-deploy --namespace=darkbot-dev --replicas 1