---
- hosts: microk8s_server
  become: yes
  gather_facts: true
  
  tasks:

    - name: Create a directory minecraft-techno if it does not exist
      ansible.builtin.file:
        path: /mnt/minecraft-techno
        state: directory

    - name: Extract foo.tgz into /mnt/minecraft-techno
      ansible.builtin.unarchive:
        src: backups/minecraft-techno/app_220213.tar
        dest: /mnt/minecraft-techno/
        extra_opts: [--strip-components=1]
        creates: "/mnt/minecraft-techno/world"
        
